// Generated by effect-auth. Run `npx effect-auth generate` to update.
// Drizzle Kit discovers top-level exported table values from schema files.
import { boolean, index, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const Users = pgTable(
  "auth_users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    name: text("name").notNull(),
    image: text("image"),
    emailVerified: boolean("email_verified").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [uniqueIndex("auth_users_email_unique").on(table.email)],
);

export const Accounts = pgTable(
  "auth_accounts",
  {
    id: text("id").primaryKey(),
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => Users.id, { onDelete: "cascade" }),
    scopes: text("scopes").array().notNull(),
    passwordHash: text("password_hash"),
    providerAccessToken: text("provider_access_token"),
    providerRefreshToken: text("provider_refresh_token"),
    providerIdToken: text("provider_id_token"),
    providerTokenType: text("provider_token_type"),
    providerTokenScope: text("provider_token_scope"),
    providerAccessTokenExpiresAt: timestamp("provider_access_token_expires_at", {
      withTimezone: true,
    }),
    providerRefreshTokenExpiresAt: timestamp("provider_refresh_token_expires_at", {
      withTimezone: true,
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex("auth_accounts_provider_account_unique").on(table.providerId, table.accountId),
    index("auth_accounts_user_id_idx").on(table.userId),
  ],
);

export const Sessions = pgTable(
  "auth_sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => Users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
  },
  (table) => [
    uniqueIndex("auth_sessions_token_hash_unique").on(table.tokenHash),
    index("auth_sessions_user_id_idx").on(table.userId),
  ],
);

export const Verifications = pgTable(
  "auth_verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    purpose: text("purpose").notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex("auth_verifications_identifier_unique").on(table.identifier),
    index("auth_verifications_value_purpose_idx").on(table.value, table.purpose),
  ],
);

export const OAuthStates = pgTable(
  "auth_oauth_states",
  {
    id: text("id").primaryKey(),
    stateHash: text("state_hash").notNull(),
    providerId: text("provider_id").notNull(),
    flow: text("flow").notNull(),
    redirectUri: text("redirect_uri").notNull(),
    scopes: text("scopes").array().notNull(),
    allowSignUp: boolean("allow_sign_up").notNull(),
    linkUserId: text("link_user_id").references(() => Users.id, { onDelete: "cascade" }),
    encryptedCodeVerifier: text("encrypted_code_verifier"),
    encryptedNonce: text("encrypted_nonce"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
  },
  (table) => [
    uniqueIndex("auth_oauth_states_state_hash_unique").on(table.stateHash),
    index("auth_oauth_states_provider_flow_idx").on(table.providerId, table.flow),
    index("auth_oauth_states_expires_at_idx").on(table.expiresAt),
    index("auth_oauth_states_link_user_id_idx").on(table.linkUserId),
  ],
);

export const authSchema = {
  Users,
  Accounts,
  Sessions,
  Verifications,
  OAuthStates,
};
