export interface GenerateDrizzlePgSchemaFileOptions {
  readonly prefix?: string;
}

export const defaultDrizzlePgSchemaOutput = "src/auth/schema.ts";
export const defaultDrizzlePgSchemaPrefix = "auth_";

const identifierPattern = /^[A-Za-z_][A-Za-z0-9_]*$/u;

// Keep this generator dependency-light: the CLI should run before apps install optional
// Drizzle peers, while the generated file is what Drizzle Kit evaluates later.
const prefixedTableNames = (prefix: string) => {
  const safePrefix = identifierPattern.test(`${prefix}users`)
    ? prefix
    : defaultDrizzlePgSchemaPrefix;
  return {
    Users: `${safePrefix}users`,
    Accounts: `${safePrefix}accounts`,
    Sessions: `${safePrefix}sessions`,
    Verifications: `${safePrefix}verifications`,
  };
};

export const generateDrizzlePgSchemaFile = (
  options: GenerateDrizzlePgSchemaFileOptions = {},
): string => {
  const prefix = options.prefix ?? defaultDrizzlePgSchemaPrefix;
  const tables = prefixedTableNames(prefix);
  return `// Generated by effect-auth. Run \`npx effect-auth generate\` to update.
// Drizzle Kit discovers top-level exported table values from schema files.
import { boolean, index, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const Users = pgTable(
  ${JSON.stringify(tables.Users)},
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    name: text("name").notNull(),
    image: text("image"),
    emailVerified: boolean("email_verified").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [uniqueIndex(${JSON.stringify(`${tables.Users}_email_unique`)}).on(table.email)],
);

export const Accounts = pgTable(
  ${JSON.stringify(tables.Accounts)},
  {
    id: text("id").primaryKey(),
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => Users.id, { onDelete: "cascade" }),
    scopes: text("scopes").array().notNull(),
    passwordHash: text("password_hash"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex(${JSON.stringify(`${tables.Accounts}_provider_account_unique`)}).on(
      table.providerId,
      table.accountId,
    ),
    index(${JSON.stringify(`${tables.Accounts}_user_id_idx`)}).on(table.userId),
  ],
);

export const Sessions = pgTable(
  ${JSON.stringify(tables.Sessions)},
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => Users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
  },
  (table) => [
    uniqueIndex(${JSON.stringify(`${tables.Sessions}_token_hash_unique`)}).on(table.tokenHash),
    index(${JSON.stringify(`${tables.Sessions}_user_id_idx`)}).on(table.userId),
  ],
);

export const Verifications = pgTable(
  ${JSON.stringify(tables.Verifications)},
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    purpose: text("purpose").notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    uniqueIndex(${JSON.stringify(`${tables.Verifications}_identifier_unique`)}).on(table.identifier),
    index(${JSON.stringify(`${tables.Verifications}_value_purpose_idx`)}).on(
      table.value,
      table.purpose,
    ),
  ],
);

export const authSchema = {
  Users,
  Accounts,
  Sessions,
  Verifications,
};
`;
};
