export {
  AuthApi,
  AuthApiEndpoints,
  AuthHttp,
  AuthHttpConfig,
  AuthHttpError,
  AuthHttpErrorMapper,
  AuthHttpHandlersLive,
  AuthHttpToken,
  AuthSession,
  CurrentAuthSession,
  SessionTokenExtractResult,
  SessionCookie,
  StateChangingRequest,
  TrustedOriginPolicy,
  TrustedOrigins,
  optionalAuth,
  requireAuth,
} from "./internal.js";

export type {
  AuthHttpConfigInput,
  AuthHttpConfigShape,
  AuthHttpErrorMapperShape,
  AuthHttpErrorResponse,
  AuthHttpMountOptions,
  AuthHttpOkResponse,
  AuthHttpOptionalAuthOptions,
  AuthHttpRequireAuthOptions,
  AuthHttpSession,
  AuthHttpSessionResponse,
  AuthHttpSignInResponse,
  AuthHttpTokenExtractor,
  AuthHttpUserResponse,
  AuthSessionShape,
  TrustedOriginPolicyShape,
} from "./internal.js";
